### ISSUE TITLE
[Registration Form SP] No error messages in the "Email" field

### ISSUE THREAD

**Issue by OksanaGuz** [ita-social-projects/OoS-Frontend#1155]
**Environment:** macOS Big Sur 11.5.1; Chrome version 101.0.4951.54.
**Reproducible:** always.
**Build found:** gcp-0.0.73

**Preconditions**

1. Go to [https://oos.dmytrominochkin.cloud/#](https://oos.dmytrominochkin.cloud/)
2. Click on "Увійти/Зареєструватися" button in header.
3. Clicks on "Зареєструватися" hyperlink.
4. Click on "Зареєструватися як надавач послуг" button.
Use this data for step 4 - dfbzdgnzdfnmxfghzaughrlzkjdrgbldgrlidghidhgbklhfghliuzhbgljzshgliuzhiguzuorhgiuzshgushgzskjgboujzsbgjkzghuzjbgilzudrhgkzijbgizjdhbfgklzjbgdfbzdgnzdfnmxfghzaughrlzkjdrgbldgrlidghidhgbklhfghliuzhbgljzshgliuzhiguzuorhgiuzshgushgzskjgboujzsbgjkzghuzjbgilzudrhgkzijbgizjdhbfgklzjbg

 **Steps to reproduce**

1. Fill "Email" field with incorrect value (e.g. gg )
2. Fill "Email" field with data which is already registered. (e.g. "vladshkrebtan@gmail.com" )
3. Fill "Email" field with not valid data (e.g. "asldkmasdasdalsdafansfilja;sfmkjbniu132i4uh192837yajkshkml.com")
4. Fill "Email" field with data more than 256 characters (take from preconditions)

**Actual result**
 There is no error massage

**Expected result**
1. "Перевірте дані email має складатися мінімум з 6-ти символів латиниці A-Z a-z та цифр 0-9 наприклад 'email@companyname.com'" Error message is shown
2. "Email" field is highlighted red with explanation in the bottom of the field "Ця електронна адреса вже використовується"
3. Field is highlighted red with error message "Будь ласка, введіть правильну електронну адресу" in the bottom of the field.
4. Field is highlighted red with error message "Будь ласка, введіть меншу кількість символів ніж 256" in the bottom of the field

Validation - https://github.com/ita-social-projects/OoS-Backend/issues/572

**User story and test case links**

User story https://github.com/ita-social-projects/OoS-Backend/issues/312
Test case [OS-571](https://jira.softserve.academy/browse/OS-571)

**Labels to be added**
"Bug", Priority ("pri: major"), Severity ("severity: minor"), Type ("UI, "Functional").

**Comment by litvinets** [comment]
@DmyMi I don't see in the code validation for email. Please, can you take a look at the validation logic and I can add the message hint after

**Comment by litvinets** [comment]
@DmyMi Can you take a look at this issue? I see there are several conditions for displaying the error, so probably it is better someone from the back end side had a look on it firstly

**Comment by litvinets** [comment]
fixed

**Comment by OksanaGuz** [comment]
Bug is still reproducible
<img width="650" alt="Снимок экрана 2022-06-27 в 12 58 50" src="https://user-images.githubusercontent.com/97882565/175915994-07e76cc9-fd1b-4cf7-812d-1a209c965f6e.png">
<img width="638" alt="Снимок экрана 2022-06-27 в 12 59 11" src="https://user-images.githubusercontent.com/97882565/175916004-73fe5389-eda9-4e57-af27-ef684cf2a536.png">
<img width="637" alt="Снимок экрана 2022-06-27 в 12 59 41" src="https://user-images.githubusercontent.com/97882565/175916008-2c2fba89-ba65-4f71-b391-d6223e28dcbf.png">

**Comment by litvinets** [comment]
please, retest it again. For this page the validation message will appear only after reloading the page. Please, accept this approach due to the technical reasons 
![image](https://user-images.githubusercontent.com/27493959/176020474-fc11784d-7d2f-4eba-b572-2af2ea0e4da3.png)

**Comment by OksanaGuz** [comment]
In case user enter already registered data, "Email" field should be highlighted red with explanation in the bottom of the field "Ця електронна адреса вже використовується"

![Uploading Снимок экрана 2022-08-01 в 17.29.28.png…]()

**Comment by litvinets** [comment]
@DmyMi check it please
