### ISSUE TITLE
[Edit Workshop] The system creates the workshop draft after editing the fields that do not require re-moderation.

### ISSUE THREAD

**Issue by volo-amare** [ita-social-projects/OoS-Frontend#2870]
**Environment:** Google Chrome Version 135.0.7049.95 (Official Build)
**Reproducible:** always
**Build found:** commit 58b180e

**Description**
Currently, changing a field that does not require re-moderation results in the creation of a workshop, which is contrary to logic and blocks subsequent changes to the workshop while the draft exists.

**Preconditions**
1. Go to https://pozashkillia-test.iea.gov.ua/#/
2. Login as the User (provider's employee)
3. Find the workshop without an existing draft OR create a workshop by Postman or Swagger (for now, the workshop is created in the backend without moderation).

**Steps to reproduce**
1. Open the editing workshop page.
2. Edit the field that does not require re-moderation, e.g. “ Вік учасників” (except for photo or description fields ("Повна назва", "Опис", etc.)).
3. Save the changes.
4. Check if the changes are saved in the workshop.
5. Check if the workshop draft has been created in the "Чернетки".
6. Try to edit the workshop and save the changes again.

**Actual result**
After editing fields that do not require re-moderation, the changes are not saved immediately to the workshop without creating a draft.
A draft is created.
You cannot make changes to the workshop while the draft exists.

https://github.com/user-attachments/assets/8b020e79-6553-4f93-b830-62ffc381a9bd

**Expected result**
After editing fields that do not require re-moderation, the changes are saved immediately in the workshop without creating a draft.

**Postconditions**
1. Delete the created workshop.

**User story and test case links**
___

**Comment by witolDark** [comment]
I have fixed the second part, but the first is a backend issue. Backend is responsible for creating drafts on update.

**Comment by volo-amare** [comment]
@witolDark The feature with redirection to draft is working, but the issue with the draft creation still exists.
